blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/chrisdewa/unbelipy/discussions
    about: A place where you can ask questions and get help from other users of the library.